---
refresh_rate: 30 seconds
appenders:
  stdout:
    kind: console
  logfile:
    kind: file
    path: "log/oa2p.log"
    encoder:
      pattern: "[{d(%Y-%m-%d %H:%M:%S %Z)(utc)}][{h({l})}][{M}] - {m}{n}"
root:
  level: warn
  appenders:
    - stdout
loggers:
  oa2p:
    level: trace
    appenders:
      - stdout
    additive: false
