[package]
name = "oauth2-provider"
version = "0.1.0"
authors = ["Andrew Turner <me@sunspar.net>"]

[dependencies]
base64 = { version = "~ 0.5.0" }
chrono = { version = "~ 0.3", features = ["serde"] }
derive_builder = { version = "~ 0.4.0" }
diesel = { version = "~ 0.12.0", features = ["postgres", "chrono"] }
diesel_codegen = { version = "~ 0.12.0", features = ["postgres"] }
dotenv = { version = "~ 0.8.0" }
lazy_static = { version = "~ 0.2.0 " }
rocket = { version = "~ 0.2.0" }
rocket_codegen = { version = "~ 0.2.0" }
rocket_contrib = { version = "~ 0.2.0" }
rand = { version = "~ 0.3" }
r2d2 = { version = "= 0.7.1" }
r2d2-diesel = { version = "~ 0.12.0" }
serde = { version = "~ 0.9.0" }
serde_derive = { version = "~ 0.9.0" }
serde_json = { version = "~ 0.9.0" }
