[package]
name = "oauth2-provider"
version = "0.1.0"
authors = ["Andrew Turner <me@sunspar.net>"]

[dependencies]
base64 = { version = "~ 0.5.0" }
bcrypt = { version = "~ 0.1.0" }
chrono = { version = "= 0.3.0", features = ["serde"] }
dotenv = { version = "= 0.8.0" }
lazy_static = { version = "~ 0.2.0" }
uuid = { version = "~ 0.4.0", features = ["serde"] }

# Data Manipulation
serde = { version = "~ 0.9.0" }
serde_derive = { version = "~ 0.9.0" }
serde_json = { version = "~ 0.9.0" }
derive_builder = { version = "= 0.4.7", features = ["private_fields"] }

# Database
diesel = { version = "= 0.12.0", features = ["postgres", "chrono", "uuid"] }
diesel_codegen = { version = "= 0.12.0", features = ["postgres"] }
r2d2 = { version = "~ 0.7.0" }
r2d2-diesel = { version = "~ 0.12.0" }

# Web Framework - Iron
iron = { version = "~ 0.5.0" }
router = { version = "~ 0.5.0" }
urlencoded = { version = "~ 0.5.0" }

# Application Logging
log = { version = "~ 0.3.0" }
log4rs = { version = "~ 0.7.0" }

# Hyper required for custom headers
hyper = { version = "~ 0.10.0" }

# uuid 0.5 has serde 1.0 support
# chrono 0.3.1 uses serde 1.0