verbose = true
max_width = 120
tab_spaces = 2
fn_call_width = 80
fn_brace_style = "PreferSameLine"
item_brace_style = "PreferSameLine"
trailing_comma = "Always"
fn_single_line = true
fn_args_paren_newline = false
reorder_imports = true
reorder_imported_names = true
hard_tabs = true
wrap_comments = true
match_block_trailing_comma = true
closure_block_indent_threshold = 0
write_mode = "Overwrite"

array_layout = "Visual"
fn_args_layout = "Visual"
fn_call_style = "Visual"